version: '3.4'

services:
  sd.dropscan.api:
    container_name: sd.dropscan.api.container-${BuildTag}
    image: alexanderkozlov/dropscan-mock-api:${BuildTag}
    restart: always
    ports: 
      - "40345:80"
  sd.simpledms.ui:
    container_name: sd.simpledms.ui.container-${BuildTag}
    image: alexanderkozlov/simple-dms-ui:${BuildTag}
    restart: always
    ports: 
      - "40347:80"
    environment:
      - ApiUrl=${ApiUrl}
      - WhitelistedDomains=${WhitelistedDomains}
    entrypoint: powershell -executionpolicy bypass "C:\scripts\ReplaceHashParamsWithEnvVariables.ps1 -FilePath 'C:\inetpub\wwwroot\main*.js'; C:\ServiceMonitor.exe w3svc"
  sd.simpledms.api:
    container_name: sd.simpledms.api.container-${BuildTag}
    image: alexanderkozlov/simple-dms-api:${BuildTag}
    restart: always
    environment:
      - dropscanApiUrl=${dropscanApiUrl}
      - ElmahConnectionString=${ElmahConnectionString}
      - SimpleDMSConnectionString=${SimpleDMSConnectionString}
    depends_on:
      - "sd.dropscan.api"
      - "simple.dms.db"
    ports: 
      - "40346:80"
  simple.dms.db:
    container_name: simple.dms.db.container-${BuildTag}
    image: microsoft/mssql-server-windows-developer
    restart: always
    ports:
      - "40350:1433"
    environment:
      - sa_password=${sa_password}
      - ACCEPT_EULA=Y
      - attach_dbs=${attach_dbs}
    volumes:
      - "C:/simple-dms-db:C:/simple-dms-db"
networks:
  default:
    external:
      name: nat
